server:
  port: 7002

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
zuul:
  routes:
#    api:
#      path: /api/**
#      serviceId: hystrix-server
    hystrix-server:
      path: /api/**