spring:
  application:
    name: mail-server
  profiles:
    active: eureka, log, datasource
  mail:
    host: smtp.qq.com
    port: 587
    username: 2388891412@qq.com
    password: 111
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 7004