server:
  port: 7005
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ingorewho/springcloud-develope/
          search-paths: config
          username: 17761256463
          password: *****

eureka:
  client:
    service-url:
     defaultZone: http://localhost:7000/eureka/



