##############注册中心配置#########
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

############断路器配置##########
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
############ribbon配置##########
#请求处理的超时时间
ribbon.ReadTimeout: 60000
#请求连接的超时时间(要小于hystrix的超时设置)
ribbon.ConnectTimeout: 20000
# 对所有操作请求都进行重试
ribbon.OkToRetryOnAllOperations: true
# 切换实例的重试次数
ribbon.MaxAutoRetriesNextServer: 2
# 对当前实例的重试次数
ribbon.MaxAutoRetries: 1

## user okhttp
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: false
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
###redis config
spring.redis:
    hostName: 127.0.0.1
    port: 7000
    password: 111
    timeout: 10000

#admin client
management:
  security:
    enabled: false

#启用shutdown
endpoints:
  shutdown:
    sensitive: false
    enabled: true
  restart:
    enabled: true
#设置session时间等
server:
  session:
    timeout: 1
  tomcat:
    basedir: .
    max-threads: 500


